name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "47 3 * * 1"
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@e8e61e86ea0a152be84d03729c02a7300065c17d
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard results
        uses: github/codeql-action/upload-sarif@276e2ce25d959f0e04da2c6b73e26b3231395db1
        with:
          sarif_file: scorecard-results.sarif
